services:
  notification-service:
    build: .
    container_name: notification_service
    restart: on-failure
    ports:
      - "50057:50057"
    depends_on:
      - notification-postgres
    env_file:
      - .env
    networks:
      - diploma-network

  notification-postgres:
    image: postgres:16
    container_name: notification_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: notification_db
    ports:
      - "5435:5432"
    volumes:
      - notification_postgres_data:/var/lib/postgresql/data
    networks:
      - diploma-network

networks:
  diploma-network:
    external: true

volumes:
  notification_postgres_data: