services:
  admin-service:
    build: .
    container_name: admin_service
    restart: on-failure
    ports:
      - "50058:50058"
    depends_on:
      - admin-postgres
    env_file:
      - .env
    networks:
      - diploma-network

  admin-postgres:
    image: postgres:16
    container_name: admin_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: admin_db
    ports:
      - "5438:5432"
    volumes:
      - admin_postgres_data:/var/lib/postgresql/data
    networks:
      - diploma-network

networks:
  diploma-network:
    external: true

volumes:
  admin_postgres_data: