services:
  feedback-service:
    build: .
    container_name: feedback_service
    restart: always
    depends_on:
      - postgres
    ports:
      - "50055:50055"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=feedback_db

  postgres:
    image: postgres:16
    container_name: feedback_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=feedback_db
    volumes:
      - feedback_postgres_data:/var/lib/postgresql/data

volumes:
  feedback_postgres_data: