services:
  feedback-service:
    build: .
    container_name: feedback_service
    restart: on-failure
    ports:
      - "50055:50055"
    depends_on:
      - feedback-postgres
    env_file:
      - .env
    networks:
      - diploma-network

  feedback-postgres:
    image: postgres:16
    container_name: feedback_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: feedback_db
    ports:
      - "5436:5432"
    volumes:
      - feedback_postgres_data:/var/lib/postgresql/data
    networks:
      - diploma-network

networks:
  diploma-network:
    external: true

volumes:
  feedback_postgres_data: