// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/route_history.proto

package routehistory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouteHistoryService_CreateHistory_FullMethodName       = "/routehistory.RouteHistoryService/CreateHistory"
	RouteHistoryService_GetUserHistory_FullMethodName      = "/routehistory.RouteHistoryService/GetUserHistory"
	RouteHistoryService_GetHistoryById_FullMethodName      = "/routehistory.RouteHistoryService/GetHistoryById"
	RouteHistoryService_UpdateHistoryStatus_FullMethodName = "/routehistory.RouteHistoryService/UpdateHistoryStatus"
)

// RouteHistoryServiceClient is the client API for RouteHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouteHistoryServiceClient interface {
	CreateHistory(ctx context.Context, in *CreateHistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	GetUserHistory(ctx context.Context, in *GetUserHistoryRequest, opts ...grpc.CallOption) (*HistoryListResponse, error)
	GetHistoryById(ctx context.Context, in *GetHistoryByIdRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	UpdateHistoryStatus(ctx context.Context, in *UpdateHistoryStatusRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
}

type routeHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouteHistoryServiceClient(cc grpc.ClientConnInterface) RouteHistoryServiceClient {
	return &routeHistoryServiceClient{cc}
}

func (c *routeHistoryServiceClient) CreateHistory(ctx context.Context, in *CreateHistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, RouteHistoryService_CreateHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeHistoryServiceClient) GetUserHistory(ctx context.Context, in *GetUserHistoryRequest, opts ...grpc.CallOption) (*HistoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryListResponse)
	err := c.cc.Invoke(ctx, RouteHistoryService_GetUserHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeHistoryServiceClient) GetHistoryById(ctx context.Context, in *GetHistoryByIdRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, RouteHistoryService_GetHistoryById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeHistoryServiceClient) UpdateHistoryStatus(ctx context.Context, in *UpdateHistoryStatusRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, RouteHistoryService_UpdateHistoryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteHistoryServiceServer is the server API for RouteHistoryService service.
// All implementations must embed UnimplementedRouteHistoryServiceServer
// for forward compatibility.
type RouteHistoryServiceServer interface {
	CreateHistory(context.Context, *CreateHistoryRequest) (*HistoryResponse, error)
	GetUserHistory(context.Context, *GetUserHistoryRequest) (*HistoryListResponse, error)
	GetHistoryById(context.Context, *GetHistoryByIdRequest) (*HistoryResponse, error)
	UpdateHistoryStatus(context.Context, *UpdateHistoryStatusRequest) (*HistoryResponse, error)
	mustEmbedUnimplementedRouteHistoryServiceServer()
}

// UnimplementedRouteHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouteHistoryServiceServer struct{}

func (UnimplementedRouteHistoryServiceServer) CreateHistory(context.Context, *CreateHistoryRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHistory not implemented")
}
func (UnimplementedRouteHistoryServiceServer) GetUserHistory(context.Context, *GetUserHistoryRequest) (*HistoryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserHistory not implemented")
}
func (UnimplementedRouteHistoryServiceServer) GetHistoryById(context.Context, *GetHistoryByIdRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoryById not implemented")
}
func (UnimplementedRouteHistoryServiceServer) UpdateHistoryStatus(context.Context, *UpdateHistoryStatusRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHistoryStatus not implemented")
}
func (UnimplementedRouteHistoryServiceServer) mustEmbedUnimplementedRouteHistoryServiceServer() {}
func (UnimplementedRouteHistoryServiceServer) testEmbeddedByValue()                             {}

// UnsafeRouteHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouteHistoryServiceServer will
// result in compilation errors.
type UnsafeRouteHistoryServiceServer interface {
	mustEmbedUnimplementedRouteHistoryServiceServer()
}

func RegisterRouteHistoryServiceServer(s grpc.ServiceRegistrar, srv RouteHistoryServiceServer) {
	// If the following call panics, it indicates UnimplementedRouteHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouteHistoryService_ServiceDesc, srv)
}

func _RouteHistoryService_CreateHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteHistoryServiceServer).CreateHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteHistoryService_CreateHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteHistoryServiceServer).CreateHistory(ctx, req.(*CreateHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteHistoryService_GetUserHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteHistoryServiceServer).GetUserHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteHistoryService_GetUserHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteHistoryServiceServer).GetUserHistory(ctx, req.(*GetUserHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteHistoryService_GetHistoryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteHistoryServiceServer).GetHistoryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteHistoryService_GetHistoryById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteHistoryServiceServer).GetHistoryById(ctx, req.(*GetHistoryByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteHistoryService_UpdateHistoryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHistoryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteHistoryServiceServer).UpdateHistoryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouteHistoryService_UpdateHistoryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteHistoryServiceServer).UpdateHistoryStatus(ctx, req.(*UpdateHistoryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouteHistoryService_ServiceDesc is the grpc.ServiceDesc for RouteHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouteHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routehistory.RouteHistoryService",
	HandlerType: (*RouteHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHistory",
			Handler:    _RouteHistoryService_CreateHistory_Handler,
		},
		{
			MethodName: "GetUserHistory",
			Handler:    _RouteHistoryService_GetUserHistory_Handler,
		},
		{
			MethodName: "GetHistoryById",
			Handler:    _RouteHistoryService_GetHistoryById_Handler,
		},
		{
			MethodName: "UpdateHistoryStatus",
			Handler:    _RouteHistoryService_UpdateHistoryStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/route_history.proto",
}
