// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/route_history.proto

package routehistory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	RouteName     string                 `protobuf:"bytes,3,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	Mood          string                 `protobuf:"bytes,4,opt,name=mood,proto3" json:"mood,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHistoryRequest) Reset() {
	*x = CreateHistoryRequest{}
	mi := &file_proto_route_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHistoryRequest) ProtoMessage() {}

func (x *CreateHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHistoryRequest.ProtoReflect.Descriptor instead.
func (*CreateHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_history_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateHistoryRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *CreateHistoryRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *CreateHistoryRequest) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

type GetUserHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserHistoryRequest) Reset() {
	*x = GetUserHistoryRequest{}
	mi := &file_proto_route_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserHistoryRequest) ProtoMessage() {}

func (x *GetUserHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetUserHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_history_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetHistoryByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryId     string                 `protobuf:"bytes,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryByIdRequest) Reset() {
	*x = GetHistoryByIdRequest{}
	mi := &file_proto_route_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryByIdRequest) ProtoMessage() {}

func (x *GetHistoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryByIdRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_history_proto_rawDescGZIP(), []int{2}
}

func (x *GetHistoryByIdRequest) GetHistoryId() string {
	if x != nil {
		return x.HistoryId
	}
	return ""
}

type UpdateHistoryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHistoryStatusRequest) Reset() {
	*x = UpdateHistoryStatusRequest{}
	mi := &file_proto_route_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHistoryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHistoryStatusRequest) ProtoMessage() {}

func (x *UpdateHistoryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHistoryStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateHistoryStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_history_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateHistoryStatusRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *UpdateHistoryStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CheckRouteCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRouteCompletedRequest) Reset() {
	*x = CheckRouteCompletedRequest{}
	mi := &file_proto_route_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRouteCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRouteCompletedRequest) ProtoMessage() {}

func (x *CheckRouteCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRouteCompletedRequest.ProtoReflect.Descriptor instead.
func (*CheckRouteCompletedRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_history_proto_rawDescGZIP(), []int{4}
}

func (x *CheckRouteCompletedRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

type CheckRouteCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCompleted   bool                   `protobuf:"varint,1,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRouteCompletedResponse) Reset() {
	*x = CheckRouteCompletedResponse{}
	mi := &file_proto_route_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRouteCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRouteCompletedResponse) ProtoMessage() {}

func (x *CheckRouteCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRouteCompletedResponse.ProtoReflect.Descriptor instead.
func (*CheckRouteCompletedResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_history_proto_rawDescGZIP(), []int{5}
}

func (x *CheckRouteCompletedResponse) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *CheckRouteCompletedResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type History struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryId     string                 `protobuf:"bytes,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RouteId       string                 `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	RouteName     string                 `protobuf:"bytes,4,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	Mood          string                 `protobuf:"bytes,5,opt,name=mood,proto3" json:"mood,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *History) Reset() {
	*x = History{}
	mi := &file_proto_route_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_proto_route_history_proto_rawDescGZIP(), []int{6}
}

func (x *History) GetHistoryId() string {
	if x != nil {
		return x.HistoryId
	}
	return ""
}

func (x *History) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *History) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *History) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *History) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *History) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *History) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       *History               `protobuf:"bytes,1,opt,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_proto_route_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_history_proto_rawDescGZIP(), []int{7}
}

func (x *HistoryResponse) GetHistory() *History {
	if x != nil {
		return x.History
	}
	return nil
}

type HistoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Histories     []*History             `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryListResponse) Reset() {
	*x = HistoryListResponse{}
	mi := &file_proto_route_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryListResponse) ProtoMessage() {}

func (x *HistoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryListResponse.ProtoReflect.Descriptor instead.
func (*HistoryListResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_history_proto_rawDescGZIP(), []int{8}
}

func (x *HistoryListResponse) GetHistories() []*History {
	if x != nil {
		return x.Histories
	}
	return nil
}

type CountRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRoutesRequest) Reset() {
	*x = CountRoutesRequest{}
	mi := &file_proto_route_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRoutesRequest) ProtoMessage() {}

func (x *CountRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRoutesRequest.ProtoReflect.Descriptor instead.
func (*CountRoutesRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_history_proto_rawDescGZIP(), []int{9}
}

type CountRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRoutes   int32                  `protobuf:"varint,1,opt,name=total_routes,json=totalRoutes,proto3" json:"total_routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRoutesResponse) Reset() {
	*x = CountRoutesResponse{}
	mi := &file_proto_route_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRoutesResponse) ProtoMessage() {}

func (x *CountRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRoutesResponse.ProtoReflect.Descriptor instead.
func (*CountRoutesResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_history_proto_rawDescGZIP(), []int{10}
}

func (x *CountRoutesResponse) GetTotalRoutes() int32 {
	if x != nil {
		return x.TotalRoutes
	}
	return 0
}

var File_proto_route_history_proto protoreflect.FileDescriptor

const file_proto_route_history_proto_rawDesc = "" +
	"\n" +
	"\x19proto/route_history.proto\x12\froutehistory\"}\n" +
	"\x14CreateHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x1d\n" +
	"\n" +
	"route_name\x18\x03 \x01(\tR\trouteName\x12\x12\n" +
	"\x04mood\x18\x04 \x01(\tR\x04mood\"0\n" +
	"\x15GetUserHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"6\n" +
	"\x15GetHistoryByIdRequest\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\tR\thistoryId\"O\n" +
	"\x1aUpdateHistoryStatusRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"7\n" +
	"\x1aCheckRouteCompletedRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\"X\n" +
	"\x1bCheckRouteCompletedResponse\x12!\n" +
	"\fis_completed\x18\x01 \x01(\bR\visCompleted\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xc6\x01\n" +
	"\aHistory\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\tR\thistoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x12\x1d\n" +
	"\n" +
	"route_name\x18\x04 \x01(\tR\trouteName\x12\x12\n" +
	"\x04mood\x18\x05 \x01(\tR\x04mood\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"B\n" +
	"\x0fHistoryResponse\x12/\n" +
	"\ahistory\x18\x01 \x01(\v2\x15.routehistory.HistoryR\ahistory\"J\n" +
	"\x13HistoryListResponse\x123\n" +
	"\thistories\x18\x01 \x03(\v2\x15.routehistory.HistoryR\thistories\"\x14\n" +
	"\x12CountRoutesRequest\"8\n" +
	"\x13CountRoutesResponse\x12!\n" +
	"\ftotal_routes\x18\x01 \x01(\x05R\vtotalRoutes2\xb9\x04\n" +
	"\x13RouteHistoryService\x12R\n" +
	"\rCreateHistory\x12\".routehistory.CreateHistoryRequest\x1a\x1d.routehistory.HistoryResponse\x12X\n" +
	"\x0eGetUserHistory\x12#.routehistory.GetUserHistoryRequest\x1a!.routehistory.HistoryListResponse\x12T\n" +
	"\x0eGetHistoryById\x12#.routehistory.GetHistoryByIdRequest\x1a\x1d.routehistory.HistoryResponse\x12^\n" +
	"\x13UpdateHistoryStatus\x12(.routehistory.UpdateHistoryStatusRequest\x1a\x1d.routehistory.HistoryResponse\x12j\n" +
	"\x13CheckRouteCompleted\x12(.routehistory.CheckRouteCompletedRequest\x1a).routehistory.CheckRouteCompletedResponse\x12R\n" +
	"\vCountRoutes\x12 .routehistory.CountRoutesRequest\x1a!.routehistory.CountRoutesResponseB\x16Z\x14./proto;routehistoryb\x06proto3"

var (
	file_proto_route_history_proto_rawDescOnce sync.Once
	file_proto_route_history_proto_rawDescData []byte
)

func file_proto_route_history_proto_rawDescGZIP() []byte {
	file_proto_route_history_proto_rawDescOnce.Do(func() {
		file_proto_route_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_route_history_proto_rawDesc), len(file_proto_route_history_proto_rawDesc)))
	})
	return file_proto_route_history_proto_rawDescData
}

var file_proto_route_history_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_route_history_proto_goTypes = []any{
	(*CreateHistoryRequest)(nil),        // 0: routehistory.CreateHistoryRequest
	(*GetUserHistoryRequest)(nil),       // 1: routehistory.GetUserHistoryRequest
	(*GetHistoryByIdRequest)(nil),       // 2: routehistory.GetHistoryByIdRequest
	(*UpdateHistoryStatusRequest)(nil),  // 3: routehistory.UpdateHistoryStatusRequest
	(*CheckRouteCompletedRequest)(nil),  // 4: routehistory.CheckRouteCompletedRequest
	(*CheckRouteCompletedResponse)(nil), // 5: routehistory.CheckRouteCompletedResponse
	(*History)(nil),                     // 6: routehistory.History
	(*HistoryResponse)(nil),             // 7: routehistory.HistoryResponse
	(*HistoryListResponse)(nil),         // 8: routehistory.HistoryListResponse
	(*CountRoutesRequest)(nil),          // 9: routehistory.CountRoutesRequest
	(*CountRoutesResponse)(nil),         // 10: routehistory.CountRoutesResponse
}
var file_proto_route_history_proto_depIdxs = []int32{
	6,  // 0: routehistory.HistoryResponse.history:type_name -> routehistory.History
	6,  // 1: routehistory.HistoryListResponse.histories:type_name -> routehistory.History
	0,  // 2: routehistory.RouteHistoryService.CreateHistory:input_type -> routehistory.CreateHistoryRequest
	1,  // 3: routehistory.RouteHistoryService.GetUserHistory:input_type -> routehistory.GetUserHistoryRequest
	2,  // 4: routehistory.RouteHistoryService.GetHistoryById:input_type -> routehistory.GetHistoryByIdRequest
	3,  // 5: routehistory.RouteHistoryService.UpdateHistoryStatus:input_type -> routehistory.UpdateHistoryStatusRequest
	4,  // 6: routehistory.RouteHistoryService.CheckRouteCompleted:input_type -> routehistory.CheckRouteCompletedRequest
	9,  // 7: routehistory.RouteHistoryService.CountRoutes:input_type -> routehistory.CountRoutesRequest
	7,  // 8: routehistory.RouteHistoryService.CreateHistory:output_type -> routehistory.HistoryResponse
	8,  // 9: routehistory.RouteHistoryService.GetUserHistory:output_type -> routehistory.HistoryListResponse
	7,  // 10: routehistory.RouteHistoryService.GetHistoryById:output_type -> routehistory.HistoryResponse
	7,  // 11: routehistory.RouteHistoryService.UpdateHistoryStatus:output_type -> routehistory.HistoryResponse
	5,  // 12: routehistory.RouteHistoryService.CheckRouteCompleted:output_type -> routehistory.CheckRouteCompletedResponse
	10, // 13: routehistory.RouteHistoryService.CountRoutes:output_type -> routehistory.CountRoutesResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_route_history_proto_init() }
func file_proto_route_history_proto_init() {
	if File_proto_route_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_route_history_proto_rawDesc), len(file_proto_route_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_route_history_proto_goTypes,
		DependencyIndexes: file_proto_route_history_proto_depIdxs,
		MessageInfos:      file_proto_route_history_proto_msgTypes,
	}.Build()
	File_proto_route_history_proto = out.File
	file_proto_route_history_proto_goTypes = nil
	file_proto_route_history_proto_depIdxs = nil
}
