services:
  route-history-service:
    build: .
    container_name: route_history_service
    restart: on-failure
    ports:
      - "50056:50056"
    depends_on:
      - route-history-postgres
    env_file:
      - .env
    networks:
      - diploma-network

  route-history-postgres:
    image: postgres:16
    container_name: route_history_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: route_history_db
    ports:
      - "5437:5432"
    volumes:
      - route_history_postgres_data:/var/lib/postgresql/data
    networks:
      - diploma-network

networks:
  diploma-network:
    external: true

volumes:
  route_history_postgres_data: