services:
  route-history-service:
    build: .
    ports:
      - "50052:50052"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=route_history_db

  postgres:
    image: postgres:15
    container_name: route_history_postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=route_history_db
    volumes:
      - route_history_postgres_data:/var/lib/postgresql/data

volumes:
  route_history_postgres_data: