syntax = "proto3";

package notification;

option go_package = "./proto;notification";

service NotificationService {
  rpc SendNotification(SendNotificationRequest) returns (NotificationResponse);
  rpc GetUserNotifications(GetUserNotificationsRequest) returns (NotificationListResponse);
  rpc MarkAsRead(MarkAsReadRequest) returns (NotificationResponse);
  rpc GetUnreadCount(GetUnreadCountRequest) returns (UnreadCountResponse);
}

message SendNotificationRequest {
  string user_id = 1;
  string message = 2;
  string type = 3;
}

message GetUserNotificationsRequest {
  string user_id = 1;
}

message MarkAsReadRequest {
  string id = 1;
}

message GetUnreadCountRequest {
  string user_id = 1;
}

message Notification {
  string id = 1;
  string user_id = 2;
  string message = 3;
  string type = 4;
  bool is_read = 5;
  string created_at = 6;
}

message NotificationResponse {
  Notification notification = 1;
}

message NotificationListResponse {
  repeated Notification notifications = 1;
}

message UnreadCountResponse {
  int32 unread_count = 1;
}