// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/feedback.proto

package feedback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Review        string                 `protobuf:"bytes,4,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeedbackRequest) Reset() {
	*x = CreateFeedbackRequest{}
	mi := &file_proto_feedback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackRequest) ProtoMessage() {}

func (x *CreateFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackRequest.ProtoReflect.Descriptor instead.
func (*CreateFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFeedbackRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateFeedbackRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *CreateFeedbackRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateFeedbackRequest) GetReview() string {
	if x != nil {
		return x.Review
	}
	return ""
}

type GetFeedbackByRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackByRouteRequest) Reset() {
	*x = GetFeedbackByRouteRequest{}
	mi := &file_proto_feedback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackByRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackByRouteRequest) ProtoMessage() {}

func (x *GetFeedbackByRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackByRouteRequest.ProtoReflect.Descriptor instead.
func (*GetFeedbackByRouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{1}
}

func (x *GetFeedbackByRouteRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

type GetFeedbackByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackByUserRequest) Reset() {
	*x = GetFeedbackByUserRequest{}
	mi := &file_proto_feedback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackByUserRequest) ProtoMessage() {}

func (x *GetFeedbackByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackByUserRequest.ProtoReflect.Descriptor instead.
func (*GetFeedbackByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{2}
}

func (x *GetFeedbackByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Feedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    string                 `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RouteId       string                 `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Review        string                 `protobuf:"bytes,5,opt,name=review,proto3" json:"review,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feedback) Reset() {
	*x = Feedback{}
	mi := &file_proto_feedback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feedback) ProtoMessage() {}

func (x *Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feedback.ProtoReflect.Descriptor instead.
func (*Feedback) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{3}
}

func (x *Feedback) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

func (x *Feedback) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Feedback) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *Feedback) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Feedback) GetReview() string {
	if x != nil {
		return x.Review
	}
	return ""
}

func (x *Feedback) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type FeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedback      *Feedback              `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackResponse) Reset() {
	*x = FeedbackResponse{}
	mi := &file_proto_feedback_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackResponse) ProtoMessage() {}

func (x *FeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackResponse.ProtoReflect.Descriptor instead.
func (*FeedbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{4}
}

func (x *FeedbackResponse) GetFeedback() *Feedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

type FeedbackListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedbacks     []*Feedback            `protobuf:"bytes,1,rep,name=feedbacks,proto3" json:"feedbacks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackListResponse) Reset() {
	*x = FeedbackListResponse{}
	mi := &file_proto_feedback_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackListResponse) ProtoMessage() {}

func (x *FeedbackListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackListResponse.ProtoReflect.Descriptor instead.
func (*FeedbackListResponse) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{5}
}

func (x *FeedbackListResponse) GetFeedbacks() []*Feedback {
	if x != nil {
		return x.Feedbacks
	}
	return nil
}

var File_proto_feedback_proto protoreflect.FileDescriptor

const file_proto_feedback_proto_rawDesc = "" +
	"\n" +
	"\x14proto/feedback.proto\x12\bfeedback\"{\n" +
	"\x15CreateFeedbackRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x16\n" +
	"\x06review\x18\x04 \x01(\tR\x06review\"6\n" +
	"\x19GetFeedbackByRouteRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\"3\n" +
	"\x18GetFeedbackByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xae\x01\n" +
	"\bFeedback\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x16\n" +
	"\x06review\x18\x05 \x01(\tR\x06review\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"B\n" +
	"\x10FeedbackResponse\x12.\n" +
	"\bfeedback\x18\x01 \x01(\v2\x12.feedback.FeedbackR\bfeedback\"H\n" +
	"\x14FeedbackListResponse\x120\n" +
	"\tfeedbacks\x18\x01 \x03(\v2\x12.feedback.FeedbackR\tfeedbacks2\x94\x02\n" +
	"\x0fFeedbackService\x12M\n" +
	"\x0eCreateFeedback\x12\x1f.feedback.CreateFeedbackRequest\x1a\x1a.feedback.FeedbackResponse\x12Y\n" +
	"\x12GetFeedbackByRoute\x12#.feedback.GetFeedbackByRouteRequest\x1a\x1e.feedback.FeedbackListResponse\x12W\n" +
	"\x11GetFeedbackByUser\x12\".feedback.GetFeedbackByUserRequest\x1a\x1e.feedback.FeedbackListResponseB!Z\x1ffeedback-service/proto;feedbackb\x06proto3"

var (
	file_proto_feedback_proto_rawDescOnce sync.Once
	file_proto_feedback_proto_rawDescData []byte
)

func file_proto_feedback_proto_rawDescGZIP() []byte {
	file_proto_feedback_proto_rawDescOnce.Do(func() {
		file_proto_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_feedback_proto_rawDesc), len(file_proto_feedback_proto_rawDesc)))
	})
	return file_proto_feedback_proto_rawDescData
}

var file_proto_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_feedback_proto_goTypes = []any{
	(*CreateFeedbackRequest)(nil),     // 0: feedback.CreateFeedbackRequest
	(*GetFeedbackByRouteRequest)(nil), // 1: feedback.GetFeedbackByRouteRequest
	(*GetFeedbackByUserRequest)(nil),  // 2: feedback.GetFeedbackByUserRequest
	(*Feedback)(nil),                  // 3: feedback.Feedback
	(*FeedbackResponse)(nil),          // 4: feedback.FeedbackResponse
	(*FeedbackListResponse)(nil),      // 5: feedback.FeedbackListResponse
}
var file_proto_feedback_proto_depIdxs = []int32{
	3, // 0: feedback.FeedbackResponse.feedback:type_name -> feedback.Feedback
	3, // 1: feedback.FeedbackListResponse.feedbacks:type_name -> feedback.Feedback
	0, // 2: feedback.FeedbackService.CreateFeedback:input_type -> feedback.CreateFeedbackRequest
	1, // 3: feedback.FeedbackService.GetFeedbackByRoute:input_type -> feedback.GetFeedbackByRouteRequest
	2, // 4: feedback.FeedbackService.GetFeedbackByUser:input_type -> feedback.GetFeedbackByUserRequest
	4, // 5: feedback.FeedbackService.CreateFeedback:output_type -> feedback.FeedbackResponse
	5, // 6: feedback.FeedbackService.GetFeedbackByRoute:output_type -> feedback.FeedbackListResponse
	5, // 7: feedback.FeedbackService.GetFeedbackByUser:output_type -> feedback.FeedbackListResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_feedback_proto_init() }
func file_proto_feedback_proto_init() {
	if File_proto_feedback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_feedback_proto_rawDesc), len(file_proto_feedback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_feedback_proto_goTypes,
		DependencyIndexes: file_proto_feedback_proto_depIdxs,
		MessageInfos:      file_proto_feedback_proto_msgTypes,
	}.Build()
	File_proto_feedback_proto = out.File
	file_proto_feedback_proto_goTypes = nil
	file_proto_feedback_proto_depIdxs = nil
}
